"""Static ISO2 → country metadata fallback for countries not in the DB seed table."""

COUNTRY_META: dict[str, dict] = {
    "AD": {"name": "Andorra", "continent": "Europe", "population": 80088},
    "AE": {"name": "United Arab Emirates", "continent": "Asia", "population": 9441129},
    "AF": {"name": "Afghanistan", "continent": "Asia", "population": 41128771},
    "AG": {"name": "Antigua and Barbuda", "continent": "North America", "population": 93763},
    "AI": {"name": "Anguilla", "continent": "North America", "population": 15753},
    "AL": {"name": "Albania", "continent": "Europe", "population": 2832439},
    "AM": {"name": "Armenia", "continent": "Asia", "population": 2971966},
    "AO": {"name": "Angola", "continent": "Africa", "population": 35588987},
    "AQ": {"name": "Antarctica", "continent": "Antarctica", "population": 1000},
    "AR": {"name": "Argentina", "continent": "South America", "population": 45510318},
    "AS": {"name": "American Samoa", "continent": "Oceania", "population": 49710},
    "AT": {"name": "Austria", "continent": "Europe", "population": 9027999},
    "AU": {"name": "Australia", "continent": "Oceania", "population": 26439111},
    "AW": {"name": "Aruba", "continent": "North America", "population": 106537},
    "AX": {"name": "Aland Islands", "continent": "Europe", "population": 30129},
    "AZ": {"name": "Azerbaijan", "continent": "Asia", "population": 10358074},
    "BA": {"name": "Bosnia and Herzegovina", "continent": "Europe", "population": 3210847},
    "BB": {"name": "Barbados", "continent": "North America", "population": 281995},
    "BD": {"name": "Bangladesh", "continent": "Asia", "population": 171186372},
    "BE": {"name": "Belgium", "continent": "Europe", "population": 11685814},
    "BF": {"name": "Burkina Faso", "continent": "Africa", "population": 22673762},
    "BG": {"name": "Bulgaria", "continent": "Europe", "population": 6878214},
    "BH": {"name": "Bahrain", "continent": "Asia", "population": 1485509},
    "BI": {"name": "Burundi", "continent": "Africa", "population": 12889576},
    "BJ": {"name": "Benin", "continent": "Africa", "population": 13352864},
    "BL": {"name": "Saint Barthelemy", "continent": "North America", "population": 10994},
    "BM": {"name": "Bermuda", "continent": "North America", "population": 64069},
    "BN": {"name": "Brunei", "continent": "Asia", "population": 449002},
    "BO": {"name": "Bolivia", "continent": "South America", "population": 12224110},
    "BQ": {"name": "Bonaire, Sint Eustatius and Saba", "continent": "North America", "population": 27148},
    "BR": {"name": "Brazil", "continent": "South America", "population": 215313498},
    "BS": {"name": "Bahamas", "continent": "North America", "population": 409984},
    "BT": {"name": "Bhutan", "continent": "Asia", "population": 782455},
    "BV": {"name": "Bouvet Island", "continent": "Antarctica", "population": 0},
    "BW": {"name": "Botswana", "continent": "Africa", "population": 2630296},
    "BY": {"name": "Belarus", "continent": "Europe", "population": 9432800},
    "BZ": {"name": "Belize", "continent": "North America", "population": 405272},
    "CA": {"name": "Canada", "continent": "North America", "population": 38781291},
    "CC": {"name": "Cocos Islands", "continent": "Asia", "population": 544},
    "CD": {"name": "Democratic Republic of the Congo", "continent": "Africa", "population": 99010212},
    "CF": {"name": "Central African Republic", "continent": "Africa", "population": 5579144},
    "CG": {"name": "Republic of the Congo", "continent": "Africa", "population": 5970424},
    "CH": {"name": "Switzerland", "continent": "Europe", "population": 8796669},
    "CI": {"name": "Ivory Coast", "continent": "Africa", "population": 28160542},
    "CK": {"name": "Cook Islands", "continent": "Oceania", "population": 17011},
    "CL": {"name": "Chile", "continent": "South America", "population": 19603733},
    "CM": {"name": "Cameroon", "continent": "Africa", "population": 27914536},
    "CN": {"name": "China", "continent": "Asia", "population": 1425887337},
    "CO": {"name": "Colombia", "continent": "South America", "population": 51874024},
    "CR": {"name": "Costa Rica", "continent": "North America", "population": 5180829},
    "CU": {"name": "Cuba", "continent": "North America", "population": 11212191},
    "CV": {"name": "Cape Verde", "continent": "Africa", "population": 593149},
    "CW": {"name": "Curacao", "continent": "North America", "population": 155014},
    "CX": {"name": "Christmas Island", "continent": "Asia", "population": 1500},
    "CY": {"name": "Cyprus", "continent": "Asia", "population": 1251488},
    "CZ": {"name": "Czech Republic", "continent": "Europe", "population": 10495295},
    "DE": {"name": "Germany", "continent": "Europe", "population": 83294633},
    "DJ": {"name": "Djibouti", "continent": "Africa", "population": 1120849},
    "DK": {"name": "Denmark", "continent": "Europe", "population": 5910913},
    "DM": {"name": "Dominica", "continent": "North America", "population": 72737},
    "DO": {"name": "Dominican Republic", "continent": "North America", "population": 11228821},
    "DZ": {"name": "Algeria", "continent": "Africa", "population": 44903225},
    "EC": {"name": "Ecuador", "continent": "South America", "population": 18001000},
    "EE": {"name": "Estonia", "continent": "Europe", "population": 1365884},
    "EG": {"name": "Egypt", "continent": "Africa", "population": 110990103},
    "EH": {"name": "Western Sahara", "continent": "Africa", "population": 652271},
    "ER": {"name": "Eritrea", "continent": "Africa", "population": 3684032},
    "ES": {"name": "Spain", "continent": "Europe", "population": 47519628},
    "ET": {"name": "Ethiopia", "continent": "Africa", "population": 123379924},
    "FI": {"name": "Finland", "continent": "Europe", "population": 5545475},
    "FJ": {"name": "Fiji", "continent": "Oceania", "population": 929766},
    "FK": {"name": "Falkland Islands", "continent": "South America", "population": 3662},
    "FM": {"name": "Micronesia", "continent": "Oceania", "population": 115021},
    "FO": {"name": "Faroe Islands", "continent": "Europe", "population": 53270},
    "FR": {"name": "France", "continent": "Europe", "population": 64756584},
    "GA": {"name": "Gabon", "continent": "Africa", "population": 2341179},
    "GB": {"name": "United Kingdom", "continent": "Europe", "population": 67736802},
    "GD": {"name": "Grenada", "continent": "North America", "population": 125438},
    "GE": {"name": "Georgia", "continent": "Asia", "population": 3728282},
    "GF": {"name": "French Guiana", "continent": "South America", "population": 312155},
    "GG": {"name": "Guernsey", "continent": "Europe", "population": 63950},
    "GH": {"name": "Ghana", "continent": "Africa", "population": 33475870},
    "GI": {"name": "Gibraltar", "continent": "Europe", "population": 32688},
    "GL": {"name": "Greenland", "continent": "North America", "population": 56643},
    "GM": {"name": "Gambia", "continent": "Africa", "population": 2705992},
    "GN": {"name": "Guinea", "continent": "Africa", "population": 13859341},
    "GP": {"name": "Guadeloupe", "continent": "North America", "population": 395700},
    "GQ": {"name": "Equatorial Guinea", "continent": "Africa", "population": 1674908},
    "GR": {"name": "Greece", "continent": "Europe", "population": 10394055},
    "GS": {"name": "South Georgia and the South Sandwich Islands", "continent": "Antarctica", "population": 30},
    "GT": {"name": "Guatemala", "continent": "North America", "population": 17608483},
    "GU": {"name": "Guam", "continent": "Oceania", "population": 171774},
    "GW": {"name": "Guinea-Bissau", "continent": "Africa", "population": 2105566},
    "GY": {"name": "Guyana", "continent": "South America", "population": 808726},
    "HK": {"name": "Hong Kong", "continent": "Asia", "population": 7494537},
    "HM": {"name": "Heard Island and McDonald Islands", "continent": "Antarctica", "population": 0},
    "HN": {"name": "Honduras", "continent": "North America", "population": 10432860},
    "HR": {"name": "Croatia", "continent": "Europe", "population": 3899000},
    "HT": {"name": "Haiti", "continent": "North America", "population": 11584996},
    "HU": {"name": "Hungary", "continent": "Europe", "population": 9597085},
    "ID": {"name": "Indonesia", "continent": "Asia", "population": 275501339},
    "IE": {"name": "Ireland", "continent": "Europe", "population": 5127170},
    "IL": {"name": "Israel", "continent": "Asia", "population": 9557500},
    "IM": {"name": "Isle of Man", "continent": "Europe", "population": 84710},
    "IN": {"name": "India", "continent": "Asia", "population": 1428627663},
    "IO": {"name": "British Indian Ocean Territory", "continent": "Asia", "population": 3000},
    "IQ": {"name": "Iraq", "continent": "Asia", "population": 44496122},
    "IR": {"name": "Iran", "continent": "Asia", "population": 88550570},
    "IS": {"name": "Iceland", "continent": "Europe", "population": 382003},
    "IT": {"name": "Italy", "continent": "Europe", "population": 58870762},
    "JE": {"name": "Jersey", "continent": "Europe", "population": 103267},
    "JM": {"name": "Jamaica", "continent": "North America", "population": 2827377},
    "JO": {"name": "Jordan", "continent": "Asia", "population": 11285869},
    "JP": {"name": "Japan", "continent": "Asia", "population": 123294513},
    "KE": {"name": "Kenya", "continent": "Africa", "population": 54027487},
    "KG": {"name": "Kyrgyzstan", "continent": "Asia", "population": 6974900},
    "KH": {"name": "Cambodia", "continent": "Asia", "population": 16767842},
    "KI": {"name": "Kiribati", "continent": "Oceania", "population": 131232},
    "KM": {"name": "Comoros", "continent": "Africa", "population": 836774},
    "KN": {"name": "Saint Kitts and Nevis", "continent": "North America", "population": 47755},
    "KP": {"name": "North Korea", "continent": "Asia", "population": 26069416},
    "KR": {"name": "South Korea", "continent": "Asia", "population": 51784059},
    "KW": {"name": "Kuwait", "continent": "Asia", "population": 4268873},
    "KY": {"name": "Cayman Islands", "continent": "North America", "population": 68136},
    "KZ": {"name": "Kazakhstan", "continent": "Asia", "population": 19621972},
    "LA": {"name": "Laos", "continent": "Asia", "population": 7529475},
    "LB": {"name": "Lebanon", "continent": "Asia", "population": 5489739},
    "LC": {"name": "Saint Lucia", "continent": "North America", "population": 179857},
    "LI": {"name": "Liechtenstein", "continent": "Europe", "population": 39327},
    "LK": {"name": "Sri Lanka", "continent": "Asia", "population": 21893579},
    "LR": {"name": "Liberia", "continent": "Africa", "population": 5302681},
    "LS": {"name": "Lesotho", "continent": "Africa", "population": 2305825},
    "LT": {"name": "Lithuania", "continent": "Europe", "population": 2859110},
    "LU": {"name": "Luxembourg", "continent": "Europe", "population": 653103},
    "LV": {"name": "Latvia", "continent": "Europe", "population": 1884490},
    "LY": {"name": "Libya", "continent": "Africa", "population": 6812341},
    "MA": {"name": "Morocco", "continent": "Africa", "population": 37457971},
    "MC": {"name": "Monaco", "continent": "Europe", "population": 36469},
    "MD": {"name": "Moldova", "continent": "Europe", "population": 2512758},
    "ME": {"name": "Montenegro", "continent": "Europe", "population": 626485},
    "MF": {"name": "Saint Martin", "continent": "North America", "population": 31791},
    "MG": {"name": "Madagascar", "continent": "Africa", "population": 29611714},
    "MH": {"name": "Marshall Islands", "continent": "Oceania", "population": 41569},
    "MK": {"name": "North Macedonia", "continent": "Europe", "population": 2085051},
    "ML": {"name": "Mali", "continent": "Africa", "population": 22593590},
    "MM": {"name": "Myanmar", "continent": "Asia", "population": 54577997},
    "MN": {"name": "Mongolia", "continent": "Asia", "population": 3398366},
    "MO": {"name": "Macao", "continent": "Asia", "population": 695168},
    "MP": {"name": "Northern Mariana Islands", "continent": "Oceania", "population": 49551},
    "MQ": {"name": "Martinique", "continent": "North America", "population": 367507},
    "MR": {"name": "Mauritania", "continent": "Africa", "population": 4736139},
    "MS": {"name": "Montserrat", "continent": "North America", "population": 4387},
    "MT": {"name": "Malta", "continent": "Europe", "population": 535064},
    "MU": {"name": "Mauritius", "continent": "Africa", "population": 1299469},
    "MV": {"name": "Maldives", "continent": "Asia", "population": 523787},
    "MW": {"name": "Malawi", "continent": "Africa", "population": 19647681},
    "MX": {"name": "Mexico", "continent": "North America", "population": 127504125},
    "MY": {"name": "Malaysia", "continent": "Asia", "population": 33938221},
    "MZ": {"name": "Mozambique", "continent": "Africa", "population": 32969518},
    "NA": {"name": "Namibia", "continent": "Africa", "population": 2604172},
    "NC": {"name": "New Caledonia", "continent": "Oceania", "population": 292991},
    "NE": {"name": "Niger", "continent": "Africa", "population": 26207977},
    "NF": {"name": "Norfolk Island", "continent": "Oceania", "population": 1748},
    "NG": {"name": "Nigeria", "continent": "Africa", "population": 218541212},
    "NI": {"name": "Nicaragua", "continent": "North America", "population": 6850540},
    "NL": {"name": "Netherlands", "continent": "Europe", "population": 17564014},
    "NO": {"name": "Norway", "continent": "Europe", "population": 5488984},
    "NP": {"name": "Nepal", "continent": "Asia", "population": 30547580},
    "NR": {"name": "Nauru", "continent": "Oceania", "population": 12668},
    "NU": {"name": "Niue", "continent": "Oceania", "population": 1934},
    "NZ": {"name": "New Zealand", "continent": "Oceania", "population": 5185288},
    "OM": {"name": "Oman", "continent": "Asia", "population": 4576298},
    "PA": {"name": "Panama", "continent": "North America", "population": 4408581},
    "PE": {"name": "Peru", "continent": "South America", "population": 34049588},
    "PF": {"name": "French Polynesia", "continent": "Oceania", "population": 306279},
    "PG": {"name": "Papua New Guinea", "continent": "Oceania", "population": 9949437},
    "PH": {"name": "Philippines", "continent": "Asia", "population": 115559009},
    "PK": {"name": "Pakistan", "continent": "Asia", "population": 235824862},
    "PL": {"name": "Poland", "continent": "Europe", "population": 38036118},
    "PM": {"name": "Saint Pierre and Miquelon", "continent": "North America", "population": 5883},
    "PN": {"name": "Pitcairn Islands", "continent": "Oceania", "population": 50},
    "PR": {"name": "Puerto Rico", "continent": "North America", "population": 3205691},
    "PS": {"name": "Palestine", "continent": "Asia", "population": 5250072},
    "PT": {"name": "Portugal", "continent": "Europe", "population": 10467366},
    "PW": {"name": "Palau", "continent": "Oceania", "population": 18055},
    "PY": {"name": "Paraguay", "continent": "South America", "population": 6780744},
    "QA": {"name": "Qatar", "continent": "Asia", "population": 2695122},
    "RE": {"name": "Reunion", "continent": "Africa", "population": 974900},
    "RO": {"name": "Romania", "continent": "Europe", "population": 19051562},
    "RS": {"name": "Serbia", "continent": "Europe", "population": 6690887},
    "RU": {"name": "Russia", "continent": "Europe", "population": 144444359},
    "RW": {"name": "Rwanda", "continent": "Africa", "population": 13776698},
    "SA": {"name": "Saudi Arabia", "continent": "Asia", "population": 36408820},
    "SB": {"name": "Solomon Islands", "continent": "Oceania", "population": 724273},
    "SC": {"name": "Seychelles", "continent": "Africa", "population": 107118},
    "SD": {"name": "Sudan", "continent": "Africa", "population": 46874204},
    "SE": {"name": "Sweden", "continent": "Europe", "population": 10486941},
    "SG": {"name": "Singapore", "continent": "Asia", "population": 5975689},
    "SH": {"name": "Saint Helena", "continent": "Africa", "population": 5396},
    "SI": {"name": "Slovenia", "continent": "Europe", "population": 2119675},
    "SJ": {"name": "Svalbard and Jan Mayen", "continent": "Europe", "population": 2562},
    "SK": {"name": "Slovakia", "continent": "Europe", "population": 5431752},
    "SL": {"name": "Sierra Leone", "continent": "Africa", "population": 8605718},
    "SM": {"name": "San Marino", "continent": "Europe", "population": 33660},
    "SN": {"name": "Senegal", "continent": "Africa", "population": 17316449},
    "SO": {"name": "Somalia", "continent": "Africa", "population": 17597511},
    "SR": {"name": "Suriname", "continent": "South America", "population": 612985},
    "SS": {"name": "South Sudan", "continent": "Africa", "population": 10913164},
    "ST": {"name": "Sao Tome and Principe", "continent": "Africa", "population": 227380},
    "SV": {"name": "El Salvador", "continent": "North America", "population": 6336392},
    "SX": {"name": "Sint Maarten", "continent": "North America", "population": 44222},
    "SY": {"name": "Syria", "continent": "Asia", "population": 21324367},
    "SZ": {"name": "Eswatini", "continent": "Africa", "population": 1192271},
    "TC": {"name": "Turks and Caicos Islands", "continent": "North America", "population": 45114},
    "TD": {"name": "Chad", "continent": "Africa", "population": 17723315},
    "TF": {"name": "French Southern Territories", "continent": "Antarctica", "population": 140},
    "TG": {"name": "Togo", "continent": "Africa", "population": 8848699},
    "TH": {"name": "Thailand", "continent": "Asia", "population": 71697030},
    "TJ": {"name": "Tajikistan", "continent": "Asia", "population": 9952787},
    "TK": {"name": "Tokelau", "continent": "Oceania", "population": 1373},
    "TL": {"name": "Timor-Leste", "continent": "Asia", "population": 1343873},
    "TM": {"name": "Turkmenistan", "continent": "Asia", "population": 6430770},
    "TN": {"name": "Tunisia", "continent": "Africa", "population": 12356117},
    "TO": {"name": "Tonga", "continent": "Oceania", "population": 106858},
    "TR": {"name": "Turkey", "continent": "Asia", "population": 85341241},
    "TT": {"name": "Trinidad and Tobago", "continent": "North America", "population": 1525663},
    "TV": {"name": "Tuvalu", "continent": "Oceania", "population": 11312},
    "TW": {"name": "Taiwan", "continent": "Asia", "population": 23923276},
    "TZ": {"name": "Tanzania", "continent": "Africa", "population": 63588334},
    "UA": {"name": "Ukraine", "continent": "Europe", "population": 43306477},
    "UG": {"name": "Uganda", "continent": "Africa", "population": 47249585},
    "UM": {"name": "United States Minor Outlying Islands", "continent": "Oceania", "population": 300},
    "US": {"name": "United States", "continent": "North America", "population": 339996563},
    "UY": {"name": "Uruguay", "continent": "South America", "population": 3422794},
    "UZ": {"name": "Uzbekistan", "continent": "Asia", "population": 35163944},
    "VA": {"name": "Vatican City", "continent": "Europe", "population": 764},
    "VC": {"name": "Saint Vincent and the Grenadines", "continent": "North America", "population": 104332},
    "VE": {"name": "Venezuela", "continent": "South America", "population": 28301696},
    "VG": {"name": "British Virgin Islands", "continent": "North America", "population": 31122},
    "VI": {"name": "U.S. Virgin Islands", "continent": "North America", "population": 99465},
    "VN": {"name": "Vietnam", "continent": "Asia", "population": 98186856},
    "VU": {"name": "Vanuatu", "continent": "Oceania", "population": 326740},
    "WF": {"name": "Wallis and Futuna", "continent": "Oceania", "population": 11369},
    "WS": {"name": "Samoa", "continent": "Oceania", "population": 225681},
    "XK": {"name": "Kosovo", "continent": "Europe", "population": 1775378},
    "YE": {"name": "Yemen", "continent": "Asia", "population": 33696614},
    "YT": {"name": "Mayotte", "continent": "Africa", "population": 326101},
    "ZA": {"name": "South Africa", "continent": "Africa", "population": 59893885},
    "ZM": {"name": "Zambia", "continent": "Africa", "population": 20017675},
    "ZW": {"name": "Zimbabwe", "continent": "Africa", "population": 16320537},
}


def get_country_info(code: str) -> dict | None:
    """Return metadata for a country code, or None if unknown."""
    return COUNTRY_META.get(code)
